[2024-09-23T09:18:38.171+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.ingest_task manual__2024-09-23T09:18:37.355416+00:00 [queued]>
[2024-09-23T09:18:38.286+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.ingest_task manual__2024-09-23T09:18:37.355416+00:00 [queued]>
[2024-09-23T09:18:38.286+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T09:18:38.286+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-09-23T09:18:38.286+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T09:18:38.306+0000] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): ingest_task> on 2024-09-23 09:18:37.355416+00:00
[2024-09-23T09:18:38.312+0000] {standard_task_runner.py:52} INFO - Started process 1233 to run task
[2024-09-23T09:18:38.314+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'db_to_offline_store', 'ingest_task', 'manual__2024-09-23T09:18:37.355416+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline/db_to_offline_store.py', '--cfg-path', '/tmp/tmpb1t_pjme', '--error-file', '/tmp/tmpqdlys_dl']
[2024-09-23T09:18:38.315+0000] {standard_task_runner.py:80} INFO - Job 115: Subtask ingest_task
[2024-09-23T09:18:38.366+0000] {task_command.py:371} INFO - Running <TaskInstance: db_to_offline_store.ingest_task manual__2024-09-23T09:18:37.355416+00:00 [running]> on host 4f3194c3b428
[2024-09-23T09:18:38.432+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=db_to_offline_store
AIRFLOW_CTX_TASK_ID=ingest_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T09:18:37.355416+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T09:18:37.355416+00:00
[2024-09-23T09:18:38.446+0000] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/data_pipeline:latest
[2024-09-23T09:18:38.449+0000] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-23T09:18:38.761+0000] {docker.py:324} INFO - 2024-09-23 09:18:38,761 - utils.logger - INFO - Ingesting...
[2024-09-23T09:18:38.868+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=db_to_offline_store, task_id=ingest_task, execution_date=20240923T091837, start_date=20240923T091838, end_date=20240923T091838
[2024-09-23T09:18:38.888+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-23T09:18:38.929+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
